name:       prefmanager
version:    0.1.0.0
github:     malob/prefmanager
author:     Malo Bourgon
maintainer: mbourgon@gmail.com
copyright:  2020 Malo Bourgon
license:    BSD3
synopsis:   A CLI utility for managing macOS preferences
category:   CLI

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/malob/prefmanager#readme>

dependencies:
- base-noprelude

library:
  source-dirs: src
  dependencies:
  - relude
  - ansi-terminal
  - async
  - async-pool
  - containers
  - hxt
  - patience
  - plist
  - prettyprinter
  - prettyprinter-ansi-terminal
  - text
  - typed-process

executables:
  prefmanager:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prefmanager
    - optparse-applicative

tests:
  prefmanager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prefmanager
