# GHC 8.10.3
resolver: nightly-2021-01-20

packages:
- .

extra-deps:
- patience-0.3
# Use fork of plist package that supports MonadFail
- github: malob/plist
  commit: 5e22be0933bf9a100868b944fa7a8b1236b99255

nix:
  shell-file: ./stack.nix
