# GHC 9.2.6
resolver: lts-20.12

extra-deps:
- patience-0.3
- base-noprelude-4.13.0.0
# Use fork of plist package that supports MonadFail
- github: malob/plist
  commit: 5e22be0933bf9a100868b944fa7a8b1236b99255

allow-newer: true

nix:
  pure: true
  shell-file: ./stack.nix
