name: "Build and Cache"
on:
  pull_request:
  push:
jobs:
  build-and-cache:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: malo
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Nix Flakes
      run: |
        nix --print-build-logs build .
        nix --print-build-logs run . -- --help
        nix --print-build-logs develop .

    - name: Nix Legacy
      run: |
        nix-build default.nix
        nix-shell shell.nix

    - name: Stack
      run: |
        stack build
        stack purge
        nix-shell shell.nix --run 'stack --nix build'
