name: "Build and Cache"
on:
  pull_request:
  push:
jobs:
  build-and-cache:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: malo
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Nix Flakes
      run: |
        nix -L build .
        nix -L run . -- --help
        nix -L develop .

    - name: Nix Legacy
      run: |
        nix-build default.nix
        nix-shell shell.nix

    - name: Stack
      run: |
        stack build
        stack purge
        nix-shell shell.nix --run 'stack --nix build'
